### ISSUE TITLE
Möglichkeit, Vorstand punktuell Geld zu bezahlen

### ISSUE THREAD

**Issue by pReya** [welcomewerkstatt/dokumente#25]
Aktuell ist es durch die Satzung quasi nahezu unmöglich Vorstandsmitgliedern Geld zu bezahlen – egal wofür.

Wir würden gerne ermöglichen, dass Vorstandsmitglieder für einmalige, punktuelle Aktionen/Tätigkeiten/Veranstaltungen Geld erhalten können - genau so wie alle anderen Mitglieder auch. Also zum Beispiel für die Durchführung eines Workshops.

Es geht also NICHT um die Entlohnung der Vorstandstätigkeit oder eine regelmäßige Entlohnung.

**Comment by carolinwagner** [comment]
Regelung ergänzt, wonach einzelne Vorstandsmitglieder nach einem Beschluss des Vorstands eine Aufwandsentschädigung erhalten können.
