### ISSUE TITLE
Bei Vereinsauflösung: Müssen Organisationen, die Vereinsvermögen erhalten würden konkret benannt werden?

### ISSUE THREAD

**Issue by pReya** [welcomewerkstatt/dokumente#28]

**Comment by carolinwagner** [comment]
Satzung eines Idealvereins: Auflösung in § 22 geregelt: https://beck-online.beck.de/Search?pagenr=1&words=vereinssatzung+muster&st=&searchid=

**Comment by pReya** [comment]
Konkrete Anfallberechtigte, denen das Vereinsvermögen bei Auflösung zufällt, müssen nicht genau benannt werden (siehe § 45 Abs. 2 BGB). Im Fall des Eintritts kann eine Mitgliederversammlung darüber entscheiden. Das erscheint mir auch sinnvoll so. Das im Voraus festzulegen stelle ich mir sehr schwierig vor. Auch Anfallberechtigte unterliegen einer gewissen "Mode" (je nach Weltlage sind gerade Zwecke X oder Y angesagt oder präsent bei den Mitgliedern). Das ganz genau in die Satzung zu schreiben würde die Zeitlosigkeit der Satzung imo deutlich verringern.
